name: ffdiamonds
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_database: ^7.2.1
  firebase_messaging: ^10.0.7
  firebase_storage: ^10.0.3
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^8.2.0
  google_mobile_ads: ^0.13.4
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+1
  intro_views_flutter: ^3.2.0
  lottie: ^1.1.0
  nb_utils: ^4.4.8
  package_info: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  overlay_support: ^0.0.4
  soundpool: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/image/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/image/
    - assets/material.png
    - assets/audios/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/font/JosefinSans.ttf
    - family: Avallon
      fonts:
        - asset: assets/font/Avallon.ttf
    - family: HillHouse
      fonts:
        - asset: assets/font/HillHouse.ttf
    - family: RoundsNeue
      fonts:
        - asset: assets/font/RoundsNeue.ttf
    - family: JusticeLeague
      fonts:
        - asset: assets/font/JusticeLeague.ttf